# Generated by Django 2.1.3 on 2018-11-19 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 19, 9, 23, 11, 324333, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
