# Generated by Django 2.1.3 on 2018-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_input_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datum'),
        ),
    ]
