# Generated by Django 2.1.2 on 2018-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muilgraaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='type',
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.IntegerField(choices=[(0, 'Muilen'), (1, 'Sex'), (2, 'Relatie')], default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='club',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
