# Generated by Django 2.1.2 on 2018-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muilgraaf', '0002_auto_20181104_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
