# Generated by Django 2.1.3 on 2018-11-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muilgraaf', '0004_auto_20181105_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_muilgraaf', 'kan muilgraaf zien wanneer ingelogd'),), 'verbose_name': 'persoon', 'verbose_name_plural': 'personen'},
        ),
    ]
