# Generated by Django 2.1.3 on 2018-11-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muilgraaf', '0005_auto_20181116_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_muilgraaf', 'Can see muilgraaf when logged in'),), 'verbose_name': 'persoon', 'verbose_name_plural': 'personen'},
        ),
    ]
