# Generated by Django 2.1.2 on 2018-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='place',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='activity',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
