# Generated by Django 2.1.2 on 2018-11-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20181102_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(verbose_name='einde'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='locatie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.FloatField(default=0, verbose_name='prijs'),
        ),
    ]
