# Generated by Django 2.1.2 on 2018-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20181105_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start'], 'verbose_name': 'activiteit', 'verbose_name_plural': 'activiteiten'},
        ),
        migrations.AddField(
            model_name='activity',
            name='googlecalendarlink',
            field=models.URLField(blank=True, null=True, verbose_name='Google calendar link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='facebooklink',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook link'),
        ),
    ]
