# Generated by Django 2.1.2 on 2018-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20181107_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='googlecalendarid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID van activiteit op Google calendar'),
        ),
    ]
