# Generated by Django 2.1.2 on 2018-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_googlecalendarid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='acitivity_images'),
        ),
    ]
