# Generated by Django 2.1.3 on 2018-11-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_addtocalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='addtocalendar',
            field=models.BooleanField(default=False, help_text='Enkel door de praeses te doen', verbose_name='Toevoegen aan Google calendar?'),
        ),
    ]
