# Generated by Django 2.1.3 on 2018-11-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20181116_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start'], 'permissions': (('add_to_calendar', 'Can add events to Google calendar'),), 'verbose_name': 'activiteit', 'verbose_name_plural': 'activiteiten'},
        ),
    ]
