# Generated by Django 2.1.2 on 2018-11-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PraesidiumMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='naam')),
                ('function', models.CharField(max_length=20, verbose_name='functie')),
                ('room', models.IntegerField(blank=True, help_text='niet verplicht', null=True, verbose_name='Kamernummer')),
                ('city', models.CharField(max_length=50, verbose_name='afkomstig van')),
                ('study', models.CharField(max_length=50, verbose_name='studie')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='naam')),
                ('logo', models.ImageField(upload_to='sponsors')),
            ],
        ),
    ]
