# Generated by Django 2.1.2 on 2018-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praesidiummember',
            options={'ordering': ['rank'], 'verbose_name': 'praesidiumlid', 'verbose_name_plural': 'praesidiumleden'},
        ),
        migrations.AddField(
            model_name='praesidiummember',
            name='image',
            field=models.ImageField(default='', upload_to='praesidiumleden', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='praesidiummember',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
