# Generated by Django 2.1.2 on 2018-11-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praesidiummember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='praesidiumleden', verbose_name='foto'),
        ),
    ]
