# Generated by Django 2.1.2 on 2018-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181116_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(default='#', help_text='Link naar website of social media'),
        ),
        migrations.AlterField(
            model_name='praesidiummember',
            name='image',
            field=models.ImageField(blank=True, help_text='Kies een vierkante foto opdat het er goed uitziet', null=True, upload_to='praesidiumleden', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(help_text='Kies een vierkantje foto opdat het er goed uitziet', upload_to='sponsors'),
        ),
    ]
