# Generated by Django 2.1.2 on 2018-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augustjes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='augustje',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Akkoord met opslag gegevens'),
        ),
    ]
